import { Component, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { PopUpComponent } from '../pop-up/pop-up.component';

@Component({
  selector: 'app-main-page',
  templateUrl: './main-page.component.html',
  styleUrls: ['./main-page.component.css']
})

export class MainPageComponent implements OnInit {



  movieList = [
    {
      movieImage: "~../../assets/images/lmAsylum.jpg",
      movieTitle: "The Asylum Little Mermaid",
      movieDescription: "https://www.imdb.com/title/tt27834173/?ref_=fn_al_tt_4",
      userReview: [
        { user: 'Tooner', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'cheese', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'rusalochka', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'auggie', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Ivoxus', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Mellieebee', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'LetSeeBlood!!', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' }

      ]
    },

    {
      movieImage: "~../../assets/images/lmSoccer.jpg",
      movieTitle: "The Soccer Football Movie",
      movieDescription: "https://www.imdb.com/title/tt22774688/",
      userReview: [
        { user: 'Tooner', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'cheese', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'rusalochka', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'auggie', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Ivoxus', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Mellieebee', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'LetSeeBlood!!', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' }

      ]
    },

    {
      movieImage: "~../../assets/images/hoodwinked.jpg",
      movieTitle: "Hoodwinked",
      movieDescription: "https://www.imdb.com/title/tt0443536/",
      userReview: [
        { user: 'Tooner', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'cheese', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'rusalochka', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'auggie', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Ivoxus', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Mellieebee', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'LetSeeBlood!!', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' }

      ]
    },

    {
      movieImage: "~../../assets/images/MummiesMoviePoster.jpg",
      movieTitle: "Mummies",
      movieDescription: "https://www.imdb.com/title/tt23177868/",
      userReview: [
        { user: 'Tooner', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'cheese', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'rusalochka', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'auggie', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Ivoxus', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Mellieebee', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'LetSeeBlood!!', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' }

      ]
    },

    {
      movieImage: "~../../assets/images/thBBS.jpg",
      movieTitle: "Tony Hawk in Boom Boom Sabotage",
      movieDescription: "https://www.imdb.com/title/tt0862921/",
      userReview: [
        { user: 'Tooner', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'cheese', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'rusalochka', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'auggie', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Ivoxus', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Mellieebee', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'LetSeeBlood!!', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' }

      ]
    },

    {
      movieImage: "~../../assets/images/goat.jpg",
      movieTitle: "Goat Story",
      movieDescription: "https://www.imdb.com/title/tt1308650/",
      userReview: [
        { user: 'Tooner', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'cheese', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'rusalochka', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'auggie', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Ivoxus', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Mellieebee', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'LetSeeBlood!!', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' }

      ]
    },

    {
      movieImage: "~../../assets/images/cinderella.jpg",
      movieTitle: "Cinderella 3D",
      movieDescription: "https://www.imdb.com/title/tt1435990/",
      userReview: [
        { user: 'Tooner', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'cheese', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'rusalochka', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'auggie', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Ivoxus', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Mellieebee', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'LetSeeBlood!!', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' }

      ]
    },

    {
      movieImage: "~../../assets/images/TLV.jpg",
      movieTitle: "The Little Vampire 3D",
      movieDescription: "https://www.imdb.com/title/tt4729560/",
      userReview: [
        { user: 'Tooner', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'cheese', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'rusalochka', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'auggie', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Ivoxus', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Mellieebee', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'LetSeeBlood!!', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' }

      ]
    },

    {
      movieImage: "~../../assets/images/SC.jpg",
      movieTitle: "Space Chimps",
      movieDescription: "https://www.imdb.com/title/tt0482603/",
      userReview: [
        { user: 'Tooner', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'cheese', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'rusalochka', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'auggie', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Ivoxus', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Mellieebee', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'LetSeeBlood!!', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' }

      ]
    },

    {
      movieImage: "~../../assets/images/Arthur_and_the_Invisibles_poster.jpg",
      movieTitle: "Arthur and the Invisibles",
      movieDescription: "https://www.imdb.com/title/tt0344854/",
      userReview: [
        { user: 'Tooner', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'cheese', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'rusalochka', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'auggie', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Ivoxus', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'Mellieebee', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' },
        { user: 'LetSeeBlood!!', review: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac mauris egestas, aliquet enim ut, mollis tellus. Vestibulum tempor dictum finibus. Ut lacus dolor, tempus et congue euismod, placerat eget velit. Cras consequat leo tempus arcu hendrerit consectetur. Donec laoreet quam nec venenatis efficitur. Sed condimentum congue finibus. Praesent egestas elit ac odio sodales ullamcorper. In sodales, neque sit amet malesuada molestie, mi nisl facilisis risus, nec vestibulum felis purus id purus. Maecenas in ornare tellus, vitae tempor elit. Sed molestie, lorem sed tincidunt condimentum, augue velit posuere urna, in efficitur libero purus ac orci. Vestibulum dolor odio, feugiat eu leo eu, pharetra sodales sem.' }

      ]
    },
  ]
    
  totalTasks = 0;

  top10Best: any = [];
  top10Worse: any = [];

  selectedPage = 'home';
  constructor(private dialogRef: MatDialog) {
    this.totalTasks = this.movieList.length;
    for (let i = 9; i >= 0; i--) {
      this.top10Best.push(this.movieList[i])
    }
    for (let i = this.movieList.length - 10; i < this.movieList.length; i++) {

      this.top10Worse.push(this.movieList[i])
    }

    ;

  }

  ngOnInit(): void {
  }

  changePage(pageName: string) {
    this.selectedPage = pageName
  }

  openDialog(theData: { user: string; review: string; }[], imbdLink:string) {
    this.dialogRef.open(PopUpComponent, {
      data: {theData, imbd:imbdLink}
    });
  }

}
